name: "RxJS Fundamentals website"

env:
  NODE_OPTIONS: --max_old_space_size=6144
  NPM_CACHE_PATH: ~/.npm
  node-version: 14.x
  website-package-name: website

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - run: npm config set cache $NPM_CACHE_PATH
      - name: Cache NPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ env.NPM_CACHE_PATH }}
          key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm ci
      - name: Build website
        run: npm run build
      - name: "Upload website build artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.website-package-name }}
          path: ./build/rxjs-fundamentals-course
          if-no-files-found: warn

  deploy:
    name: Deploy website to GitHub Pages
    if: >
      github.ref == 'refs/heads/main' && (github.event_name ==
      'workflow_dispatch' || github.event_name == 'push')
    needs: build
    runs-on: ubuntu-latest

    env:
      package-path: ./static-website/

    steps:
      # necessary for JamesIves/github-pages-deploy-action
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.website-package-name }}
          path: ${{ env.package-path }}

      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: ${{ env.package-path }}
